import { useEffect, useRef, useState } from "react";
import { createImageThumbnail } from "@/shared/services/image";

export interface ImagePreviewProps {
  file: File;
  src: string;
  alt: string;
  className?: string;
}

/**
 * @human Renders an image preview. When the browser cannot display the format
 * itself (e.g. HEIC), it falls back to a thumbnail generated by the image worker.
 */
export function ImagePreview({ file, src, alt, className }: ImagePreviewProps) {
  const [thumbnailUrl, setThumbnailUrl] = useState<string | null>(null);
  const requested = useRef(false);
  const mounted = useRef(true);

  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);

  useEffect(() => {
    requested.current = false;
    setThumbnailUrl(null);
  }, [file]);

  useEffect(() => {
    return () => {
      if (thumbnailUrl) URL.revokeObjectURL(thumbnailUrl);
    };
  }, [thumbnailUrl]);

  const handleError = async () => {
    if (requested.current) return;
    requested.current = true;
    try {
      const blob = await createImageThumbnail(file);
      const url = URL.createObjectURL(blob);
      if (mounted.current) setThumbnailUrl(url);
      else URL.revokeObjectURL(url);
    } catch {
      // Neither the browser nor the worker could decode the file.
    }
  };

  return <img src={thumbnailUrl ?? src} alt={alt} className={className} onError={handleError} />;
}
