/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Base64EncoderRouteImport } from './routes/base64-encoder'
import { Route as DiffCheckerRouteImport } from './routes/diff-checker'
import { Route as EncryptPdfRouteImport } from './routes/encrypt-pdf'
import { Route as HashGeneratorRouteImport } from './routes/hash-generator'
import { Route as ImageColorPaletteRouteImport } from './routes/image-color-palette'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as ImageResizeRouteImport } from './routes/image-resize'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as JsonYamlConverterRouteImport } from './routes/json-yaml-converter'
import { Route as JwtDecoderRouteImport } from './routes/jwt-decoder'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as PdfToMarkdownRouteImport } from './routes/pdf-to-markdown'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PythonPlaygroundRouteImport } from './routes/python-playground'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as RegexTesterRouteImport } from './routes/regex-tester'
import { Route as RemoveImageMetadataRouteImport } from './routes/remove-image-metadata'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as TimestampConverterRouteImport } from './routes/timestamp-converter'
import { Route as UnlockPdfRouteImport } from './routes/unlock-pdf'
import { Route as UrlEncoderRouteImport } from './routes/url-encoder'
import { Route as UuidGeneratorRouteImport } from './routes/uuid-generator'
import { Route as XmlFormatterRouteImport } from './routes/xml-formatter'
import { Route as Char123categoryChar125ToolsRouteImport } from './routes/{$category}-tools'
import { Route as ApiToolsDotjsonRouteImport } from './routes/api/tools[.]json'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ImageConverterIndexRouteImport } from './routes/image-converter/index'
import { Route as ImageConverterConversionRouteImport } from './routes/image-converter/$conversion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64EncoderRoute = Base64EncoderRouteImport.update({
  id: '/base64-encoder',
  path: '/base64-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffCheckerRoute = DiffCheckerRouteImport.update({
  id: '/diff-checker',
  path: '/diff-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptPdfRoute = EncryptPdfRouteImport.update({
  id: '/encrypt-pdf',
  path: '/encrypt-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HashGeneratorRoute = HashGeneratorRouteImport.update({
  id: '/hash-generator',
  path: '/hash-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageColorPaletteRoute = ImageColorPaletteRouteImport.update({
  id: '/image-color-palette',
  path: '/image-color-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageResizeRoute = ImageResizeRouteImport.update({
  id: '/image-resize',
  path: '/image-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonYamlConverterRoute = JsonYamlConverterRouteImport.update({
  id: '/json-yaml-converter',
  path: '/json-yaml-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDecoderRoute = JwtDecoderRouteImport.update({
  id: '/jwt-decoder',
  path: '/jwt-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToMarkdownRoute = PdfToMarkdownRouteImport.update({
  id: '/pdf-to-markdown',
  path: '/pdf-to-markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonPlaygroundRoute = PythonPlaygroundRouteImport.update({
  id: '/python-playground',
  path: '/python-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexTesterRoute = RegexTesterRouteImport.update({
  id: '/regex-tester',
  path: '/regex-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveImageMetadataRoute = RemoveImageMetadataRouteImport.update({
  id: '/remove-image-metadata',
  path: '/remove-image-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampConverterRoute = TimestampConverterRouteImport.update({
  id: '/timestamp-converter',
  path: '/timestamp-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockPdfRoute = UnlockPdfRouteImport.update({
  id: '/unlock-pdf',
  path: '/unlock-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncoderRoute = UrlEncoderRouteImport.update({
  id: '/url-encoder',
  path: '/url-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidGeneratorRoute = UuidGeneratorRouteImport.update({
  id: '/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlFormatterRoute = XmlFormatterRouteImport.update({
  id: '/xml-formatter',
  path: '/xml-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123categoryChar125ToolsRoute =
  Char123categoryChar125ToolsRouteImport.update({
    id: '/{$category}-tools',
    path: '/{$category}-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiToolsDotjsonRoute = ApiToolsDotjsonRouteImport.update({
  id: '/api/tools.json',
  path: '/api/tools.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConverterIndexRoute = ImageConverterIndexRouteImport.update({
  id: '/image-converter/',
  path: '/image-converter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConverterConversionRoute =
  ImageConverterConversionRouteImport.update({
    id: '/image-converter/$conversion',
    path: '/image-converter/$conversion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64-encoder': typeof Base64EncoderRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/image-color-palette': typeof ImageColorPaletteRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-yaml-converter': typeof JsonYamlConverterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-markdown': typeof PdfToMarkdownRoute
  '/privacy': typeof PrivacyRoute
  '/python-playground': typeof PythonPlaygroundRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/remove-image-metadata': typeof RemoveImageMetadataRoute
  '/split-pdf': typeof SplitPdfRoute
  '/timestamp-converter': typeof TimestampConverterRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/xml-formatter': typeof XmlFormatterRoute
  '/{$category}-tools': typeof Char123categoryChar125ToolsRoute
  '/api/tools.json': typeof ApiToolsDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/blog/': typeof BlogIndexRoute
  '/image-converter/': typeof ImageConverterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64-encoder': typeof Base64EncoderRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/image-color-palette': typeof ImageColorPaletteRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-yaml-converter': typeof JsonYamlConverterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-markdown': typeof PdfToMarkdownRoute
  '/privacy': typeof PrivacyRoute
  '/python-playground': typeof PythonPlaygroundRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/remove-image-metadata': typeof RemoveImageMetadataRoute
  '/split-pdf': typeof SplitPdfRoute
  '/timestamp-converter': typeof TimestampConverterRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/xml-formatter': typeof XmlFormatterRoute
  '/{$category}-tools': typeof Char123categoryChar125ToolsRoute
  '/api/tools.json': typeof ApiToolsDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/blog': typeof BlogIndexRoute
  '/image-converter': typeof ImageConverterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64-encoder': typeof Base64EncoderRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/image-color-palette': typeof ImageColorPaletteRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-yaml-converter': typeof JsonYamlConverterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-markdown': typeof PdfToMarkdownRoute
  '/privacy': typeof PrivacyRoute
  '/python-playground': typeof PythonPlaygroundRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/remove-image-metadata': typeof RemoveImageMetadataRoute
  '/split-pdf': typeof SplitPdfRoute
  '/timestamp-converter': typeof TimestampConverterRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/xml-formatter': typeof XmlFormatterRoute
  '/{$category}-tools': typeof Char123categoryChar125ToolsRoute
  '/api/tools.json': typeof ApiToolsDotjsonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/blog/': typeof BlogIndexRoute
  '/image-converter/': typeof ImageConverterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/base64-encoder'
    | '/diff-checker'
    | '/encrypt-pdf'
    | '/hash-generator'
    | '/image-color-palette'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/json-yaml-converter'
    | '/jwt-decoder'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-to-markdown'
    | '/privacy'
    | '/python-playground'
    | '/qr-generator'
    | '/regex-tester'
    | '/remove-image-metadata'
    | '/split-pdf'
    | '/timestamp-converter'
    | '/unlock-pdf'
    | '/url-encoder'
    | '/uuid-generator'
    | '/xml-formatter'
    | '/{$category}-tools'
    | '/api/tools.json'
    | '/blog/$slug'
    | '/image-converter/$conversion'
    | '/blog/'
    | '/image-converter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/base64-encoder'
    | '/diff-checker'
    | '/encrypt-pdf'
    | '/hash-generator'
    | '/image-color-palette'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/json-yaml-converter'
    | '/jwt-decoder'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-to-markdown'
    | '/privacy'
    | '/python-playground'
    | '/qr-generator'
    | '/regex-tester'
    | '/remove-image-metadata'
    | '/split-pdf'
    | '/timestamp-converter'
    | '/unlock-pdf'
    | '/url-encoder'
    | '/uuid-generator'
    | '/xml-formatter'
    | '/{$category}-tools'
    | '/api/tools.json'
    | '/blog/$slug'
    | '/image-converter/$conversion'
    | '/blog'
    | '/image-converter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/base64-encoder'
    | '/diff-checker'
    | '/encrypt-pdf'
    | '/hash-generator'
    | '/image-color-palette'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/json-yaml-converter'
    | '/jwt-decoder'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-to-markdown'
    | '/privacy'
    | '/python-playground'
    | '/qr-generator'
    | '/regex-tester'
    | '/remove-image-metadata'
    | '/split-pdf'
    | '/timestamp-converter'
    | '/unlock-pdf'
    | '/url-encoder'
    | '/uuid-generator'
    | '/xml-formatter'
    | '/{$category}-tools'
    | '/api/tools.json'
    | '/blog/$slug'
    | '/image-converter/$conversion'
    | '/blog/'
    | '/image-converter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Base64EncoderRoute: typeof Base64EncoderRoute
  DiffCheckerRoute: typeof DiffCheckerRoute
  EncryptPdfRoute: typeof EncryptPdfRoute
  HashGeneratorRoute: typeof HashGeneratorRoute
  ImageColorPaletteRoute: typeof ImageColorPaletteRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageResizeRoute: typeof ImageResizeRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JsonYamlConverterRoute: typeof JsonYamlConverterRoute
  JwtDecoderRoute: typeof JwtDecoderRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MergePdfRoute: typeof MergePdfRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PdfToImageRoute: typeof PdfToImageRoute
  PdfToMarkdownRoute: typeof PdfToMarkdownRoute
  PrivacyRoute: typeof PrivacyRoute
  PythonPlaygroundRoute: typeof PythonPlaygroundRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  RegexTesterRoute: typeof RegexTesterRoute
  RemoveImageMetadataRoute: typeof RemoveImageMetadataRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TimestampConverterRoute: typeof TimestampConverterRoute
  UnlockPdfRoute: typeof UnlockPdfRoute
  UrlEncoderRoute: typeof UrlEncoderRoute
  UuidGeneratorRoute: typeof UuidGeneratorRoute
  XmlFormatterRoute: typeof XmlFormatterRoute
  Char123categoryChar125ToolsRoute: typeof Char123categoryChar125ToolsRoute
  ApiToolsDotjsonRoute: typeof ApiToolsDotjsonRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ImageConverterConversionRoute: typeof ImageConverterConversionRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ImageConverterIndexRoute: typeof ImageConverterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64-encoder': {
      id: '/base64-encoder'
      path: '/base64-encoder'
      fullPath: '/base64-encoder'
      preLoaderRoute: typeof Base64EncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-checker': {
      id: '/diff-checker'
      path: '/diff-checker'
      fullPath: '/diff-checker'
      preLoaderRoute: typeof DiffCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypt-pdf': {
      id: '/encrypt-pdf'
      path: '/encrypt-pdf'
      fullPath: '/encrypt-pdf'
      preLoaderRoute: typeof EncryptPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-generator': {
      id: '/hash-generator'
      path: '/hash-generator'
      fullPath: '/hash-generator'
      preLoaderRoute: typeof HashGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-color-palette': {
      id: '/image-color-palette'
      path: '/image-color-palette'
      fullPath: '/image-color-palette'
      preLoaderRoute: typeof ImageColorPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-resize': {
      id: '/image-resize'
      path: '/image-resize'
      fullPath: '/image-resize'
      preLoaderRoute: typeof ImageResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-yaml-converter': {
      id: '/json-yaml-converter'
      path: '/json-yaml-converter'
      fullPath: '/json-yaml-converter'
      preLoaderRoute: typeof JsonYamlConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-decoder': {
      id: '/jwt-decoder'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder'
      preLoaderRoute: typeof JwtDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-markdown': {
      id: '/pdf-to-markdown'
      path: '/pdf-to-markdown'
      fullPath: '/pdf-to-markdown'
      preLoaderRoute: typeof PdfToMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-playground': {
      id: '/python-playground'
      path: '/python-playground'
      fullPath: '/python-playground'
      preLoaderRoute: typeof PythonPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-tester': {
      id: '/regex-tester'
      path: '/regex-tester'
      fullPath: '/regex-tester'
      preLoaderRoute: typeof RegexTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-image-metadata': {
      id: '/remove-image-metadata'
      path: '/remove-image-metadata'
      fullPath: '/remove-image-metadata'
      preLoaderRoute: typeof RemoveImageMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamp-converter': {
      id: '/timestamp-converter'
      path: '/timestamp-converter'
      fullPath: '/timestamp-converter'
      preLoaderRoute: typeof TimestampConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock-pdf': {
      id: '/unlock-pdf'
      path: '/unlock-pdf'
      fullPath: '/unlock-pdf'
      preLoaderRoute: typeof UnlockPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encoder': {
      id: '/url-encoder'
      path: '/url-encoder'
      fullPath: '/url-encoder'
      preLoaderRoute: typeof UrlEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid-generator': {
      id: '/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof UuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-formatter': {
      id: '/xml-formatter'
      path: '/xml-formatter'
      fullPath: '/xml-formatter'
      preLoaderRoute: typeof XmlFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$category}-tools': {
      id: '/{$category}-tools'
      path: '/{$category}-tools'
      fullPath: '/{$category}-tools'
      preLoaderRoute: typeof Char123categoryChar125ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools.json': {
      id: '/api/tools.json'
      path: '/api/tools.json'
      fullPath: '/api/tools.json'
      preLoaderRoute: typeof ApiToolsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter/': {
      id: '/image-converter/'
      path: '/image-converter'
      fullPath: '/image-converter/'
      preLoaderRoute: typeof ImageConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter/$conversion': {
      id: '/image-converter/$conversion'
      path: '/image-converter/$conversion'
      fullPath: '/image-converter/$conversion'
      preLoaderRoute: typeof ImageConverterConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Base64EncoderRoute: Base64EncoderRoute,
  DiffCheckerRoute: DiffCheckerRoute,
  EncryptPdfRoute: EncryptPdfRoute,
  HashGeneratorRoute: HashGeneratorRoute,
  ImageColorPaletteRoute: ImageColorPaletteRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageResizeRoute: ImageResizeRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JsonYamlConverterRoute: JsonYamlConverterRoute,
  JwtDecoderRoute: JwtDecoderRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MergePdfRoute: MergePdfRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PdfToImageRoute: PdfToImageRoute,
  PdfToMarkdownRoute: PdfToMarkdownRoute,
  PrivacyRoute: PrivacyRoute,
  PythonPlaygroundRoute: PythonPlaygroundRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  RegexTesterRoute: RegexTesterRoute,
  RemoveImageMetadataRoute: RemoveImageMetadataRoute,
  SplitPdfRoute: SplitPdfRoute,
  TimestampConverterRoute: TimestampConverterRoute,
  UnlockPdfRoute: UnlockPdfRoute,
  UrlEncoderRoute: UrlEncoderRoute,
  UuidGeneratorRoute: UuidGeneratorRoute,
  XmlFormatterRoute: XmlFormatterRoute,
  Char123categoryChar125ToolsRoute: Char123categoryChar125ToolsRoute,
  ApiToolsDotjsonRoute: ApiToolsDotjsonRoute,
  BlogSlugRoute: BlogSlugRoute,
  ImageConverterConversionRoute: ImageConverterConversionRoute,
  BlogIndexRoute: BlogIndexRoute,
  ImageConverterIndexRoute: ImageConverterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
