/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EncryptPdfRouteImport } from './routes/encrypt-pdf'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as ImageResizeRouteImport } from './routes/image-resize'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as ImageToolsRouteImport } from './routes/image-tools'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as PdfToolsRouteImport } from './routes/pdf-tools'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as UnlockPdfRouteImport } from './routes/unlock-pdf'
import { Route as ApiDottoolsJsonRouteImport } from './routes/api[.]tools.json'
import { Route as ImageConverterIndexRouteImport } from './routes/image-converter/index'
import { Route as ImageConverterConversionRouteImport } from './routes/image-converter/$conversion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptPdfRoute = EncryptPdfRouteImport.update({
  id: '/encrypt-pdf',
  path: '/encrypt-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageResizeRoute = ImageResizeRouteImport.update({
  id: '/image-resize',
  path: '/image-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsRoute = ImageToolsRouteImport.update({
  id: '/image-tools',
  path: '/image-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsRoute = PdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockPdfRoute = UnlockPdfRouteImport.update({
  id: '/unlock-pdf',
  path: '/unlock-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDottoolsJsonRoute = ApiDottoolsJsonRouteImport.update({
  id: '/api.tools/json',
  path: '/api.tools/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConverterIndexRoute = ImageConverterIndexRouteImport.update({
  id: '/image-converter/',
  path: '/image-converter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConverterConversionRoute =
  ImageConverterConversionRouteImport.update({
    id: '/image-converter/$conversion',
    path: '/image-converter/$conversion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/image-tools': typeof ImageToolsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split-pdf': typeof SplitPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/api.tools/json': typeof ApiDottoolsJsonRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/image-converter/': typeof ImageConverterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/image-tools': typeof ImageToolsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split-pdf': typeof SplitPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/api.tools/json': typeof ApiDottoolsJsonRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/image-converter': typeof ImageConverterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/encrypt-pdf': typeof EncryptPdfRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/image-tools': typeof ImageToolsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/split-pdf': typeof SplitPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/api.tools/json': typeof ApiDottoolsJsonRoute
  '/image-converter/$conversion': typeof ImageConverterConversionRoute
  '/image-converter/': typeof ImageConverterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/encrypt-pdf'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/image-tools'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-tools'
    | '/privacy'
    | '/qr-generator'
    | '/split-pdf'
    | '/unlock-pdf'
    | '/api.tools/json'
    | '/image-converter/$conversion'
    | '/image-converter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/encrypt-pdf'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/image-tools'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-tools'
    | '/privacy'
    | '/qr-generator'
    | '/split-pdf'
    | '/unlock-pdf'
    | '/api.tools/json'
    | '/image-converter/$conversion'
    | '/image-converter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/encrypt-pdf'
    | '/image-compressor'
    | '/image-resize'
    | '/image-to-pdf'
    | '/image-tools'
    | '/llms.txt'
    | '/merge-pdf'
    | '/password-generator'
    | '/pdf-to-image'
    | '/pdf-tools'
    | '/privacy'
    | '/qr-generator'
    | '/split-pdf'
    | '/unlock-pdf'
    | '/api.tools/json'
    | '/image-converter/$conversion'
    | '/image-converter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EncryptPdfRoute: typeof EncryptPdfRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageResizeRoute: typeof ImageResizeRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  ImageToolsRoute: typeof ImageToolsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MergePdfRoute: typeof MergePdfRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PdfToImageRoute: typeof PdfToImageRoute
  PdfToolsRoute: typeof PdfToolsRoute
  PrivacyRoute: typeof PrivacyRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  SplitPdfRoute: typeof SplitPdfRoute
  UnlockPdfRoute: typeof UnlockPdfRoute
  ApiDottoolsJsonRoute: typeof ApiDottoolsJsonRoute
  ImageConverterConversionRoute: typeof ImageConverterConversionRoute
  ImageConverterIndexRoute: typeof ImageConverterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypt-pdf': {
      id: '/encrypt-pdf'
      path: '/encrypt-pdf'
      fullPath: '/encrypt-pdf'
      preLoaderRoute: typeof EncryptPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-resize': {
      id: '/image-resize'
      path: '/image-resize'
      fullPath: '/image-resize'
      preLoaderRoute: typeof ImageResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools': {
      id: '/image-tools'
      path: '/image-tools'
      fullPath: '/image-tools'
      preLoaderRoute: typeof ImageToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools': {
      id: '/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof PdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock-pdf': {
      id: '/unlock-pdf'
      path: '/unlock-pdf'
      fullPath: '/unlock-pdf'
      preLoaderRoute: typeof UnlockPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api.tools/json': {
      id: '/api.tools/json'
      path: '/api.tools/json'
      fullPath: '/api.tools/json'
      preLoaderRoute: typeof ApiDottoolsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter/': {
      id: '/image-converter/'
      path: '/image-converter'
      fullPath: '/image-converter/'
      preLoaderRoute: typeof ImageConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter/$conversion': {
      id: '/image-converter/$conversion'
      path: '/image-converter/$conversion'
      fullPath: '/image-converter/$conversion'
      preLoaderRoute: typeof ImageConverterConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EncryptPdfRoute: EncryptPdfRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageResizeRoute: ImageResizeRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  ImageToolsRoute: ImageToolsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MergePdfRoute: MergePdfRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PdfToImageRoute: PdfToImageRoute,
  PdfToolsRoute: PdfToolsRoute,
  PrivacyRoute: PrivacyRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  SplitPdfRoute: SplitPdfRoute,
  UnlockPdfRoute: UnlockPdfRoute,
  ApiDottoolsJsonRoute: ApiDottoolsJsonRoute,
  ImageConverterConversionRoute: ImageConverterConversionRoute,
  ImageConverterIndexRoute: ImageConverterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
